const Resume = require('../models/Resume');
const geminiService = require('../services/geminiService');

exports.simulatePath = async (req, res) => {
  try {
    const { resumeId, targetRole } = req.body;
    
    const resume = await Resume.findById(resumeId);
    if (!resume) return res.status(404).json({ message: 'Resume not found' });
    if (resume.user_id.toString() !== req.user.id) return res.status(403).json({ message: 'Not authorized' });

    const resumeContext = JSON.stringify({
      experience: resume.experience,
      skills: resume.skills,
      education: resume.education
    });

    const simulation = await geminiService.simulateCareerPath(resumeContext, targetRole);
    
    // Completely ephemeral
    res.json({
      targetRole,
      simulation,
      disclaimer: "This is an illustrative simulation generated by AI based on real market patterns and your current skill gaps. It is not authoritative career advice or a guarantee."
    });
  } catch (error) {
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};
