const mongoose = require('mongoose');

const notificationSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  type: { 
    type: String, 
    enum: [
      'question_answered', 
      'review_upvoted', 
      'answer_upvoted', 
      'review_reported_resolved', 
      'question_upvoted',
      'event_approved',
      'event_rejected',
      'event_reminder',
      'event_updated',
      'event_cancelled',
      'waitlist_confirmed',
      'event_feedback_request',
      'team_request',
      'team_request_accepted',
      'course_reminder',
      'course_streak_milestone',
      'booking_requested',
      'booking_confirmed',
      'booking_cancelled',
      'session_reminder',
      'review_received',
      'mentor_application_status',
      'ama_registration_confirmed',
      'ama_reminder',
      'ama_cancelled',
      'application_submitted',
      'application_status_changed',
      'new_applicant',
      'recruiter_verified',
      'recruiter_rejected',
      'job_auto_hidden',
      'job_deleted_by_admin',
      'recruiter_banned',
      'application_deadline_approaching',
      'profile_viewed',
      'job_invite_received',
      'job_alert_match',
      'company_new_job',
      'live_session_reminder',
      'live_session_invite',
      'quiz_reported',
      'quiz_deleted',
      'leaderboard_overtaken',
      'live_session_results',
      'badge_earned',
      'dispute_update',
      'referral_credit_earned',
      'subscription_renewal',
      'subscription_failure',
      'forum_reply',
      'cohort_session_scheduled',
      'learning_path_step_suggestion'
    ],
    required: true
  },
  relatedCollegeId: { type: mongoose.Schema.Types.ObjectId, ref: 'College', default: null },
  relatedJob: { type: mongoose.Schema.Types.ObjectId, ref: 'Job', default: null },
  relatedApplication: { type: mongoose.Schema.Types.ObjectId, ref: 'JobApplication', default: null },
  relatedQuiz: { type: mongoose.Schema.Types.ObjectId, ref: 'Quiz', default: null },
  relatedLiveSession: { type: mongoose.Schema.Types.ObjectId, ref: 'LiveSession', default: null },
  relatedContentId: { type: mongoose.Schema.Types.ObjectId, default: null }, // questionId/reviewId/answerId
  message: { type: String, required: true },
  actionUrl: { type: String },
  channel: { type: String, enum: ['in_app', 'email', 'both'], default: 'in_app' },
  deliveryChannels: [{ type: String, enum: ['in_app', 'email', 'push'] }],
  emailSent: { type: Boolean, default: false },
  emailSentAt: { type: Date },
  emailFailureReason: { type: String },
  isRead: { type: Boolean, default: false }
}, { timestamps: true });

notificationSchema.index({ userId: 1, isRead: 1 });

module.exports = mongoose.model('Notification', notificationSchema);
