import { precacheAndRoute } from 'workbox-precaching';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly } from 'workbox-strategies';

declare let self: ServiceWorkerGlobalScope;

// Precache static assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Background Sync for offline booking actions (cancel/reschedule)
const bookingSyncPlugin = new BackgroundSyncPlugin('booking-queue', {
  maxRetentionTime: 24 * 60 // Retry for up to 24 hours
});

// Cache upcoming bookings for offline viewing
import { StaleWhileRevalidate } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

registerRoute(
  /\/api\/mentors\/bookings\/me/,
  new StaleWhileRevalidate({
    cacheName: 'upcoming-bookings-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200]
      }),
      new ExpirationPlugin({
        maxEntries: 1, // We only need the latest response
        maxAgeSeconds: 24 * 60 * 60 // 24 hours
      })
    ]
  }),
  'GET'
);

registerRoute(
  /\/api\/mentors\/bookings\/.*/,
  new NetworkOnly({
    plugins: [bookingSyncPlugin]
  }),
  'PUT'
);

registerRoute(
  /\/api\/mentors\/bookings\/.*/,
  new NetworkOnly({
    plugins: [bookingSyncPlugin]
  }),
  'DELETE'
);

// Push Notifications
self.addEventListener('push', (event) => {
  let data = { title: 'New Notification', body: '', url: '/' };
  
  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data.body = event.data.text();
    }
  }

  const options = {
    body: data.body,
    icon: data.icon || '/vite.svg',
    data: {
      url: data.data?.url || data.url || '/'
    }
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const urlToOpen = event.notification.data.url;
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window' }).then((windowClients) => {
      // Check if there is already a window/tab open with the target URL
      for (var i = 0; i < windowClients.length; i++) {
        var client = windowClients[i];
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      // If not, open a new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
